name: Continuous Integration

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - "master"
jobs:
  Test:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9-alpine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run Tests
        run: mix test --cover

  Linting:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9-alpine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Fetch Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: formatter
        run: mix format --check-formatted

      - name: credo
        run: mix credo
